

SCHEMAS:
  rainfall:
    'CREATE TABLE IF NOT EXISTS rainfall (
      DATE VARCHAR(32),
      UNIX_TIME INTEGER,
      [POONDI] FLOAT,
      [CHOLA VARAM] FLOAT,
      [RED HILLS] FLOAT,
      [TAMARAI PAKKAM] FLOAT,
      [CHEMBARAM BAKKAM] FLOAT,
      [KORATTUR ANICUT] FLOAT,
      [VEERANAM] FLOAT,
      [NUNGAM BAKKAM] FLOAT,
      [MEENAM BAKKAM] FLOAT,
      PRIMARY KEY (UNIX_TIME))'


